### ISSUE TITLE
Remove non-Python dependencies

### ISSUE THREAD

**Issue by tsalo** [eurunuela/pySPFM#18]
I don't know if this is something you're interested in, but it would be awesome if pySPFM didn't require AFNI to run. I could be wrong, but it looks like the only places where AFNI is called are in `hrf_afni` and `update_header`:

https://github.com/eurunuela/pySPFM/blob/d69907cd3a8f0455b44504c74a73ee93915d4409/pySPFM/deconvolution/hrf_generator.py#L72

https://github.com/eurunuela/pySPFM/blob/dca806578adc86f55943a708d18bf02a2d4155ab/pySPFM/io.py#L62

It seems like `hrf_afni` could be replaced with something from `nilearn.glm` (e.g., [`nilearn.glm.first_level.spm_hrf`](https://nilearn.github.io/dev/modules/generated/nilearn.glm.first_level.spm_hrf.html#nilearn.glm.first_level.spm_hrf)). I don't know about `update_header`, but updating a HEAD/BRIK pair's header seems like something `nibabel` _should_ be able to do.

**Comment by eurunuela** [comment]
I would love to make that 100% Pythonic. It would make the testing suite so much simpler.

I'll have a look at those. The good thing about using AFNI is it lets you choose the shape of the HRF. I don't know if the options provided by Nilearn are the same.

**Comment by eurunuela** [comment]
We have used the GAM HRF in AFNI's `3dDeconvolve`.

Another option would be to let users input a `.1D` file with the HRF.

By the way, I don't think it's possible to add to the history on the header using `nibabel`.

**Comment by tsalo** [comment]
The GAM HRF is the one that SPM uses, right? In that case, that should work. Nilearn can also handle custom HRFs as long as they're functions that predict values over time, if you wanted to define one of your own.

>By the way, I don't think it's possible to add to the history on the header using nibabel.

Darn... maybe it's worth nibabel issue then.

**Comment by eurunuela** [comment]
> The GAM HRF is the one that SPM uses, right? In that case, that should work. Nilearn can also handle custom HRFs as long as they're functions that predict values over time, if you wanted to define one of your own.

Will have that in mind then. Thank you @tsalo, this is very useful!

> Darn... maybe it's worth nibabel issue then.

Will open one!

**Comment by tsalo** [comment]
What do you think of adding an option for generating BIDS-like sidecar files with the history, as an alternative? So folks could either use AFNI with subprocess or just pure Python, with an additional `.json` file in the output directory.
